# @format
name: Feature Request
description: Suggest a new feature or propose an enhancement
title: "(feat-scope): [Short Summary of Feature]"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Provide a concise overview of the feature or enhancement you’d like to propose.
  - type: textarea
    attributes:
      label: What problem does this address?
      description: |
        Please describe the problem you are trying to solve with this feature.
        Include any relevant context or background information.
      placeholder: "E.g., Users must manually X, which is time-consuming when Y happens..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: |
        Describe how you’d like this feature to work.
      placeholder: "E.g., Add a `--auto-rotate` flag that…"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      placeholder: If applicable, add any additional context or screenshots to help explain your feature request.
    validations:
      required: false
