name: Plugin Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plugin-check:
    uses: lubusIN/.github/.github/workflows/plugin-check.yml@main
    with:
      plugin-slug: visual-blueprint-builder
    secrets: inherit
