name: Sync to Playground

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target-branch:
        description: Target branch to sync generated files to
        required: false
        default: playground
      force-folder:
        description: Folder path to force-sync
        required: false
        default: build/
  workflow_call:
    inputs:
      target-branch:
        required: false
        type: string
        default: playground
      force-folder:
        required: false
        type: string
        default: build/

jobs:
  build-and-push:
    uses: lubusIN/.github/.github/workflows/sync-playground.yml@main
    with:
      target-branch: ${{ (github.event_name == 'workflow_call' && inputs.target-branch) || (github.event_name == 'workflow_dispatch' && github.event.inputs.target-branch) || 'playground' }}
      force-folder: ${{ (github.event_name == 'workflow_call' && inputs.force-folder) || (github.event_name == 'workflow_dispatch' && github.event.inputs.force-folder) || 'build/' }}
    secrets: inherit
